version: "3.8"

services:
  frontend:
    build:
      context: ./sk0-front
      dockerfile: Dockerfile.development
    ports:
      - "4200:4200"
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./sk0-front
          target: /app
          ignore:
            - node_modules/
            - .angular/
            - www/
        - action: rebuild
          path: package.json

  backend:
    build:
      context: ./sk0-back
      dockerfile: Dockerfile.development
    ports:
      - "${BACKEND_PORT}:3000"
    develop:
      watch:
        - action: sync
          path: ./sk0-back
          target: /usr/src/app
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: package.json
  database:
    image: postgres:alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
