version: '3.8'

services:
  frontend:
    build: ./sk0-front
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend

  backend:
    build: ./sk0-back
    ports:
      - "${BACKEND_PORT}:3000"
    env_file:
      - ./sk0-back/.env.development
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
