version: '3.8'

services:
  frontend:
    build:
      context: ./sk0-front
      dockerfile: Dockerfile.development
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build: 
      context: ./sk0-back
      dockerfile: Dockerfile.development
    ports:
      - "${BACKEND_PORT}:3000"
    env_file:
      - ./sk0-back/.env.development
    develop:
      watch:
        - action: sync
          path: ./sk0-back
          target: /usr/src/app
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: package.json
