version: '3.8'

services:
  frontend:
    # build: ./sk0-front/Dockerfile.development
    build:
      context: ./sk0-front
      dockerfile: Dockerfile.development
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build: ./sk0-back
    ports:
      - "${BACKEND_PORT}:3000"
    env_file:
      - ./sk0-back/.env.development
