### List users
GET http://localhost:3000/users

### Register user
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "name": "Test User 1",
  "email": "ab@c.de",
  "password": "Password1"
}


### Login user
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "ab@cc.de",
  "password": "Password1"
}