name: CI - Frontend

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

defaults:
  run:
    working-directory: sk0-front

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm ci
      - name: Testing
        run: npm run test
      - name: Build
        run: npm run build
